package com.lgec.enlacefi.spei.integration.h2h;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.0
 * 2014-06-02T16:08:17.132-05:00
 * Generated source version: 3.0.0
 * 
 */
@WebServiceClient(name = "SpeiServicesImplService", 
                  wsdlLocation = "SpeiServices",
                  targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/") 
public class SpeiServicesImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://h2h.integration.spei.enlacefi.lgec.com/", "SpeiServicesImplService");
    public final static QName SpeiServicesImplPort = new QName("http://h2h.integration.spei.enlacefi.lgec.com/", "SpeiServicesImplPort");
    static {
        URL url = SpeiServicesImplService.class.getResource("SpeiServices");
        if (url == null) {
            url = SpeiServicesImplService.class.getClassLoader().getResource("SpeiServices");
        } 
        if (url == null) {
            java.util.logging.Logger.getLogger(SpeiServicesImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "SpeiServices");
        }       
        WSDL_LOCATION = url;
    }

    public SpeiServicesImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SpeiServicesImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SpeiServicesImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SpeiServicesImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SpeiServicesImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SpeiServicesImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns SpeiServices
     */
    @WebEndpoint(name = "SpeiServicesImplPort")
    public SpeiServices getSpeiServicesImplPort() {
        return super.getPort(SpeiServicesImplPort, SpeiServices.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SpeiServices
     */
    @WebEndpoint(name = "SpeiServicesImplPort")
    public SpeiServices getSpeiServicesImplPort(WebServiceFeature... features) {
        return super.getPort(SpeiServicesImplPort, SpeiServices.class, features);
    }

}
