package com.lgec.enlacefi.spei.integration.h2h;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.0
 * 2014-06-02T16:08:17.112-05:00
 * Generated source version: 3.0.0
 * 
 */
@WebService(targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", name = "SpeiServices")
@XmlSeeAlso({ObjectFactory.class})
public interface SpeiServices {

    @RequestWrapper(localName = "registraDetalleErrorRecepcion", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.RegistraDetalleErrorRecepcion")
    @WebMethod
    @ResponseWrapper(localName = "registraDetalleErrorRecepcionResponse", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.RegistraDetalleErrorRecepcionResponse")
    public void registraDetalleErrorRecepcion(
        @WebParam(name = "id", targetNamespace = "")
        java.lang.Integer id,
        @WebParam(name = "detalleError", targetNamespace = "")
        java.lang.String detalleError
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "devuelveOrdenClaveRastreo", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.DevuelveOrdenClaveRastreo")
    @WebMethod
    @ResponseWrapper(localName = "devuelveOrdenClaveRastreoResponse", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.DevuelveOrdenClaveRastreoResponse")
    public com.lgec.enlacefi.spei.integration.h2h.SpeiServiceResponse devuelveOrdenClaveRastreo(
        @WebParam(name = "claveInstitucion", targetNamespace = "")
        java.lang.Integer claveInstitucion,
        @WebParam(name = "claveRastreo", targetNamespace = "")
        java.lang.String claveRastreo,
        @WebParam(name = "causaDevolucion", targetNamespace = "")
        java.lang.Integer causaDevolucion,
        @WebParam(name = "nuevoRastreo", targetNamespace = "")
        java.lang.String nuevoRastreo,
        @WebParam(name = "medioEntrega", targetNamespace = "")
        java.lang.Integer medioEntrega,
        @WebParam(name = "usuario", targetNamespace = "")
        java.lang.String usuario
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "consultaOrdenEnviada", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.ConsultaOrdenEnviada")
    @WebMethod
    @ResponseWrapper(localName = "consultaOrdenEnviadaResponse", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.ConsultaOrdenEnviadaResponse")
    public com.lgec.enlacefi.spei.integration.h2h.OrdenPagoWS consultaOrdenEnviada(
        @WebParam(name = "idOrden", targetNamespace = "")
        java.lang.Integer idOrden
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "consultaSaldos", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.ConsultaSaldos")
    @WebMethod
    @ResponseWrapper(localName = "consultaSaldosResponse", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.ConsultaSaldosResponse")
    public com.lgec.enlacefi.spei.integration.h2h.ConsolidadoSaldosDTO consultaSaldos(
        @WebParam(name = "claveInstitucion", targetNamespace = "")
        java.lang.Integer claveInstitucion
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "devuelveOrdenRazonRechazo", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.DevuelveOrdenRazonRechazo")
    @WebMethod
    @ResponseWrapper(localName = "devuelveOrdenRazonRechazoResponse", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.DevuelveOrdenRazonRechazoResponse")
    public com.lgec.enlacefi.spei.integration.h2h.SpeiServiceResponse devuelveOrdenRazonRechazo(
        @WebParam(name = "idOrden", targetNamespace = "")
        java.lang.Integer idOrden,
        @WebParam(name = "causaDevolucion", targetNamespace = "")
        java.lang.Integer causaDevolucion,
        @WebParam(name = "nuevoRastreo", targetNamespace = "")
        java.lang.String nuevoRastreo,
        @WebParam(name = "medioEntrega", targetNamespace = "")
        java.lang.Integer medioEntrega,
        @WebParam(name = "usuario", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(name = "razonRechazo", targetNamespace = "")
        java.lang.String razonRechazo
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "registraTraspaso", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.RegistraTraspaso")
    @WebMethod
    @ResponseWrapper(localName = "registraTraspasoResponse", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.RegistraTraspasoResponse")
    public com.lgec.enlacefi.spei.integration.h2h.SpeiServiceResponse registraTraspaso(
        @WebParam(name = "traspaso", targetNamespace = "")
        com.lgec.enlacefi.spei.integration.h2h.TraspasoWS traspaso
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "tiempoEntregaCargo", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.TiempoEntregaCargo")
    @WebMethod
    @ResponseWrapper(localName = "tiempoEntregaCargoResponse", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.TiempoEntregaCargoResponse")
    public java.lang.Long tiempoEntregaCargo(
        @WebParam(name = "idOrden", targetNamespace = "")
        java.lang.Integer idOrden
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "registraOrdenesTraspasos", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.RegistraOrdenesTraspasos")
    @WebMethod
    @ResponseWrapper(localName = "registraOrdenesTraspasosResponse", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.RegistraOrdenesTraspasosResponse")
    public com.lgec.enlacefi.spei.integration.h2h.ResponseOrdenTraspaso registraOrdenesTraspasos(
        @WebParam(name = "ordenesTraspasos", targetNamespace = "")
        com.lgec.enlacefi.spei.integration.h2h.OrdenesTraspasos ordenesTraspasos
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "confirmaCargo", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.ConfirmaCargo")
    @WebMethod
    @ResponseWrapper(localName = "confirmaCargoResponse", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.ConfirmaCargoResponse")
    public com.lgec.enlacefi.spei.integration.h2h.SpeiServiceResponse confirmaCargo(
        @WebParam(name = "idOrden", targetNamespace = "")
        java.lang.Integer idOrden,
        @WebParam(name = "razonCancelacion", targetNamespace = "")
        java.lang.String razonCancelacion,
        @WebParam(name = "nuevoEstado", targetNamespace = "")
        java.lang.String nuevoEstado,
        @WebParam(name = "folio", targetNamespace = "")
        java.lang.String folio
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "tiempoEntregaAbonoRastreo", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.TiempoEntregaAbonoRastreo")
    @WebMethod
    @ResponseWrapper(localName = "tiempoEntregaAbonoRastreoResponse", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.TiempoEntregaAbonoRastreoResponse")
    public java.lang.Long tiempoEntregaAbonoRastreo(
        @WebParam(name = "fechaOperacion", targetNamespace = "")
        java.lang.Integer fechaOperacion,
        @WebParam(name = "rastreo", targetNamespace = "")
        java.lang.String rastreo,
        @WebParam(name = "instContraparte", targetNamespace = "")
        java.lang.Integer instContraparte
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "devuelveOrden", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.DevuelveOrden")
    @WebMethod
    @ResponseWrapper(localName = "devuelveOrdenResponse", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.DevuelveOrdenResponse")
    public com.lgec.enlacefi.spei.integration.h2h.SpeiServiceResponse devuelveOrden(
        @WebParam(name = "idOrden", targetNamespace = "")
        java.lang.Integer idOrden,
        @WebParam(name = "causaDevolucion", targetNamespace = "")
        java.lang.Integer causaDevolucion,
        @WebParam(name = "nuevoRastreo", targetNamespace = "")
        java.lang.String nuevoRastreo,
        @WebParam(name = "medioEntrega", targetNamespace = "")
        java.lang.Integer medioEntrega,
        @WebParam(name = "usuario", targetNamespace = "")
        java.lang.String usuario
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "estadoOperaciones", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.EstadoOperaciones")
    @WebMethod
    @ResponseWrapper(localName = "estadoOperacionesResponse", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.EstadoOperacionesResponse")
    public com.lgec.enlacefi.spei.integration.h2h.EstadoOperacionesResponseWS estadoOperaciones(
        @WebParam(name = "empresa", targetNamespace = "")
        java.lang.String empresa,
        @WebParam(name = "recorreSubempresas", targetNamespace = "")
        boolean recorreSubempresas,
        @WebParam(name = "estados", targetNamespace = "")
        java.lang.String estados,
        @WebParam(name = "tipoOperacion", targetNamespace = "")
        java.lang.String tipoOperacion
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "traspasoEntreCuentas", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.TraspasoEntreCuentas")
    @WebMethod
    @ResponseWrapper(localName = "traspasoEntreCuentasResponse", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.TraspasoEntreCuentasResponse")
    public com.lgec.enlacefi.spei.integration.h2h.SpeiServiceResponse traspasoEntreCuentas(
        @WebParam(name = "cuentaOrigen", targetNamespace = "")
        java.lang.String cuentaOrigen,
        @WebParam(name = "cuentaDestino", targetNamespace = "")
        java.lang.String cuentaDestino,
        @WebParam(name = "monto", targetNamespace = "")
        java.lang.String monto,
        @WebParam(name = "usuario", targetNamespace = "")
        java.lang.String usuario
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "confirmaAbono", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.ConfirmaAbono")
    @WebMethod
    @ResponseWrapper(localName = "confirmaAbonoResponse", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.ConfirmaAbonoResponse")
    public com.lgec.enlacefi.spei.integration.h2h.SpeiServiceResponse confirmaAbono(
        @WebParam(name = "fechaOperacion", targetNamespace = "")
        java.lang.Integer fechaOperacion,
        @WebParam(name = "institucionContraparte", targetNamespace = "")
        java.lang.Integer institucionContraparte,
        @WebParam(name = "claveRastreo", targetNamespace = "")
        java.lang.String claveRastreo,
        @WebParam(name = "rfc", targetNamespace = "")
        java.lang.String rfc
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "consultaNominaTesofeFechaOperacion", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.ConsultaNominaTesofeFechaOperacion")
    @WebMethod
    @ResponseWrapper(localName = "consultaNominaTesofeFechaOperacionResponse", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.ConsultaNominaTesofeFechaOperacionResponse")
    public com.lgec.enlacefi.spei.integration.h2h.NominaTesofeWS consultaNominaTesofeFechaOperacion(
        @WebParam(name = "institucion", targetNamespace = "")
        java.lang.Integer institucion,
        @WebParam(name = "fechaOperacion", targetNamespace = "")
        java.lang.Integer fechaOperacion
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "confirmaAbonoDelay", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.ConfirmaAbonoDelay")
    @WebMethod
    @ResponseWrapper(localName = "confirmaAbonoDelayResponse", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.ConfirmaAbonoDelayResponse")
    public com.lgec.enlacefi.spei.integration.h2h.SpeiServiceResponse confirmaAbonoDelay(
        @WebParam(name = "idEF", targetNamespace = "")
        java.lang.Integer idEF,
        @WebParam(name = "rfc", targetNamespace = "")
        java.lang.String rfc,
        @WebParam(name = "delay", targetNamespace = "")
        java.lang.Long delay
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "tiempoEntregaCargoRastreo", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.TiempoEntregaCargoRastreo")
    @WebMethod
    @ResponseWrapper(localName = "tiempoEntregaCargoRastreoResponse", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.TiempoEntregaCargoRastreoResponse")
    public java.lang.Long tiempoEntregaCargoRastreo(
        @WebParam(name = "fechaOperacion", targetNamespace = "")
        java.lang.Integer fechaOperacion,
        @WebParam(name = "rastreo", targetNamespace = "")
        java.lang.String rastreo,
        @WebParam(name = "instOperante", targetNamespace = "")
        java.lang.Integer instOperante
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "consultaOrdenes", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.ConsultaOrdenes")
    @WebMethod
    @ResponseWrapper(localName = "consultaOrdenesResponse", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.ConsultaOrdenesResponse")
    public java.util.List<com.lgec.enlacefi.spei.integration.h2h.OrdenPagoWS> consultaOrdenes(
        @WebParam(name = "tipoOrden", targetNamespace = "")
        java.lang.String tipoOrden,
        @WebParam(name = "fechaLiqInicial", targetNamespace = "")
        java.lang.Integer fechaLiqInicial,
        @WebParam(name = "fechaLiqFinal", targetNamespace = "")
        java.lang.Integer fechaLiqFinal,
        @WebParam(name = "institucionOperante", targetNamespace = "")
        java.lang.Integer institucionOperante,
        @WebParam(name = "institucionCotraparte", targetNamespace = "")
        java.lang.Integer institucionCotraparte,
        @WebParam(name = "nombreOrdenante", targetNamespace = "")
        java.lang.String nombreOrdenante,
        @WebParam(name = "nombreBeneficiario", targetNamespace = "")
        java.lang.String nombreBeneficiario,
        @WebParam(name = "cveRastreo", targetNamespace = "")
        java.lang.String cveRastreo,
        @WebParam(name = "cuentaOrdenante", targetNamespace = "")
        java.lang.String cuentaOrdenante,
        @WebParam(name = "cuentaBeneficiario", targetNamespace = "")
        java.lang.String cuentaBeneficiario,
        @WebParam(name = "monto", targetNamespace = "")
        java.math.BigDecimal monto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "registraOrden", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.RegistraOrden")
    @WebMethod
    @ResponseWrapper(localName = "registraOrdenResponse", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.RegistraOrdenResponse")
    public com.lgec.enlacefi.spei.integration.h2h.SpeiServiceResponse registraOrden(
        @WebParam(name = "ordenPago", targetNamespace = "")
        com.lgec.enlacefi.spei.integration.h2h.OrdenPagoWS ordenPago
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "tiempoEntregaAbono", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.TiempoEntregaAbono")
    @WebMethod
    @ResponseWrapper(localName = "tiempoEntregaAbonoResponse", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.TiempoEntregaAbonoResponse")
    public java.lang.Long tiempoEntregaAbono(
        @WebParam(name = "idOrden", targetNamespace = "")
        java.lang.Integer idOrden
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "consultaOrdenEnviadaRastreo", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.ConsultaOrdenEnviadaRastreo")
    @WebMethod
    @ResponseWrapper(localName = "consultaOrdenEnviadaRastreoResponse", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.ConsultaOrdenEnviadaRastreoResponse")
    public com.lgec.enlacefi.spei.integration.h2h.OrdenPagoWS consultaOrdenEnviadaRastreo(
        @WebParam(name = "fechaOperacion", targetNamespace = "")
        java.lang.Integer fechaOperacion,
        @WebParam(name = "operante", targetNamespace = "")
        java.lang.Integer operante,
        @WebParam(name = "rastreo", targetNamespace = "")
        java.lang.String rastreo
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "consultaNominaTesofe", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.ConsultaNominaTesofe")
    @WebMethod
    @ResponseWrapper(localName = "consultaNominaTesofeResponse", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.ConsultaNominaTesofeResponse")
    public com.lgec.enlacefi.spei.integration.h2h.NominaTesofeWS consultaNominaTesofe(
        @WebParam(name = "institucion", targetNamespace = "")
        java.lang.Integer institucion
    );

    @RequestWrapper(localName = "registraDetalleErrorEnvio", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.RegistraDetalleErrorEnvio")
    @WebMethod
    @ResponseWrapper(localName = "registraDetalleErrorEnvioResponse", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.RegistraDetalleErrorEnvioResponse")
    public void registraDetalleErrorEnvio(
        @WebParam(name = "id", targetNamespace = "")
        java.lang.Integer id,
        @WebParam(name = "detalleError", targetNamespace = "")
        java.lang.String detalleError
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "registraOrdenes", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.RegistraOrdenes")
    @WebMethod
    @ResponseWrapper(localName = "registraOrdenesResponse", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.RegistraOrdenesResponse")
    public java.util.List<com.lgec.enlacefi.spei.integration.h2h.SpeiServiceResponse> registraOrdenes(
        @WebParam(name = "ordenesPago", targetNamespace = "")
        java.util.List<com.lgec.enlacefi.spei.integration.h2h.OrdenPagoWS> ordenesPago
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "confirmaAbonoId", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.ConfirmaAbonoId")
    @WebMethod
    @ResponseWrapper(localName = "confirmaAbonoIdResponse", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.ConfirmaAbonoIdResponse")
    public com.lgec.enlacefi.spei.integration.h2h.SpeiServiceResponse confirmaAbonoId(
        @WebParam(name = "idEF", targetNamespace = "")
        java.lang.Integer idEF,
        @WebParam(name = "rfc", targetNamespace = "")
        java.lang.String rfc
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "consultaOrdenRecibida", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.ConsultaOrdenRecibida")
    @WebMethod
    @ResponseWrapper(localName = "consultaOrdenRecibidaResponse", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.ConsultaOrdenRecibidaResponse")
    public com.lgec.enlacefi.spei.integration.h2h.OrdenPagoWS consultaOrdenRecibida(
        @WebParam(name = "idOrden", targetNamespace = "")
        java.lang.Integer idOrden
    );
}
