
package com.lgec.enlacefi.spei.integration.h2h;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.0.0
 * 2014-06-02T16:08:17.074-05:00
 * Generated source version: 3.0.0
 * 
 */
public final class SpeiServices_SpeiServicesImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://h2h.integration.spei.enlacefi.lgec.com/", "SpeiServicesImplService");

    private SpeiServices_SpeiServicesImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = SpeiServicesImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        SpeiServicesImplService ss = new SpeiServicesImplService(wsdlURL, SERVICE_NAME);
        SpeiServices port = ss.getSpeiServicesImplPort();  
        
        {
        System.out.println("Invoking registraDetalleErrorRecepcion...");
        java.lang.Integer _registraDetalleErrorRecepcion_id = null;
        java.lang.String _registraDetalleErrorRecepcion_detalleError = "";
        port.registraDetalleErrorRecepcion(_registraDetalleErrorRecepcion_id, _registraDetalleErrorRecepcion_detalleError);


        }
        {
        System.out.println("Invoking devuelveOrdenClaveRastreo...");
        java.lang.Integer _devuelveOrdenClaveRastreo_claveInstitucion = null;
        java.lang.String _devuelveOrdenClaveRastreo_claveRastreo = "";
        java.lang.Integer _devuelveOrdenClaveRastreo_causaDevolucion = null;
        java.lang.String _devuelveOrdenClaveRastreo_nuevoRastreo = "";
        java.lang.Integer _devuelveOrdenClaveRastreo_medioEntrega = null;
        java.lang.String _devuelveOrdenClaveRastreo_usuario = "";
        com.lgec.enlacefi.spei.integration.h2h.SpeiServiceResponse _devuelveOrdenClaveRastreo__return = port.devuelveOrdenClaveRastreo(_devuelveOrdenClaveRastreo_claveInstitucion, _devuelveOrdenClaveRastreo_claveRastreo, _devuelveOrdenClaveRastreo_causaDevolucion, _devuelveOrdenClaveRastreo_nuevoRastreo, _devuelveOrdenClaveRastreo_medioEntrega, _devuelveOrdenClaveRastreo_usuario);
        System.out.println("devuelveOrdenClaveRastreo.result=" + _devuelveOrdenClaveRastreo__return);


        }
        {
        System.out.println("Invoking consultaOrdenEnviada...");
        java.lang.Integer _consultaOrdenEnviada_idOrden = null;
        com.lgec.enlacefi.spei.integration.h2h.OrdenPagoWS _consultaOrdenEnviada__return = port.consultaOrdenEnviada(_consultaOrdenEnviada_idOrden);
        System.out.println("consultaOrdenEnviada.result=" + _consultaOrdenEnviada__return);


        }
        {
        System.out.println("Invoking consultaSaldos...");
        java.lang.Integer _consultaSaldos_claveInstitucion = null;
        com.lgec.enlacefi.spei.integration.h2h.ConsolidadoSaldosDTO _consultaSaldos__return = port.consultaSaldos(_consultaSaldos_claveInstitucion);
        System.out.println("consultaSaldos.result=" + _consultaSaldos__return);


        }
        {
        System.out.println("Invoking devuelveOrdenRazonRechazo...");
        java.lang.Integer _devuelveOrdenRazonRechazo_idOrden = null;
        java.lang.Integer _devuelveOrdenRazonRechazo_causaDevolucion = null;
        java.lang.String _devuelveOrdenRazonRechazo_nuevoRastreo = "";
        java.lang.Integer _devuelveOrdenRazonRechazo_medioEntrega = null;
        java.lang.String _devuelveOrdenRazonRechazo_usuario = "";
        java.lang.String _devuelveOrdenRazonRechazo_razonRechazo = "";
        com.lgec.enlacefi.spei.integration.h2h.SpeiServiceResponse _devuelveOrdenRazonRechazo__return = port.devuelveOrdenRazonRechazo(_devuelveOrdenRazonRechazo_idOrden, _devuelveOrdenRazonRechazo_causaDevolucion, _devuelveOrdenRazonRechazo_nuevoRastreo, _devuelveOrdenRazonRechazo_medioEntrega, _devuelveOrdenRazonRechazo_usuario, _devuelveOrdenRazonRechazo_razonRechazo);
        System.out.println("devuelveOrdenRazonRechazo.result=" + _devuelveOrdenRazonRechazo__return);


        }
        {
        System.out.println("Invoking registraTraspaso...");
        com.lgec.enlacefi.spei.integration.h2h.TraspasoWS _registraTraspaso_traspaso = null;
        com.lgec.enlacefi.spei.integration.h2h.SpeiServiceResponse _registraTraspaso__return = port.registraTraspaso(_registraTraspaso_traspaso);
        System.out.println("registraTraspaso.result=" + _registraTraspaso__return);


        }
        {
        System.out.println("Invoking tiempoEntregaCargo...");
        java.lang.Integer _tiempoEntregaCargo_idOrden = null;
        java.lang.Long _tiempoEntregaCargo__return = port.tiempoEntregaCargo(_tiempoEntregaCargo_idOrden);
        System.out.println("tiempoEntregaCargo.result=" + _tiempoEntregaCargo__return);


        }
        {
        System.out.println("Invoking registraOrdenesTraspasos...");
        com.lgec.enlacefi.spei.integration.h2h.OrdenesTraspasos _registraOrdenesTraspasos_ordenesTraspasos = null;
        com.lgec.enlacefi.spei.integration.h2h.ResponseOrdenTraspaso _registraOrdenesTraspasos__return = port.registraOrdenesTraspasos(_registraOrdenesTraspasos_ordenesTraspasos);
        System.out.println("registraOrdenesTraspasos.result=" + _registraOrdenesTraspasos__return);


        }
        {
        System.out.println("Invoking confirmaCargo...");
        java.lang.Integer _confirmaCargo_idOrden = null;
        java.lang.String _confirmaCargo_razonCancelacion = "";
        java.lang.String _confirmaCargo_nuevoEstado = "";
        java.lang.String _confirmaCargo_folio = "";
        com.lgec.enlacefi.spei.integration.h2h.SpeiServiceResponse _confirmaCargo__return = port.confirmaCargo(_confirmaCargo_idOrden, _confirmaCargo_razonCancelacion, _confirmaCargo_nuevoEstado, _confirmaCargo_folio);
        System.out.println("confirmaCargo.result=" + _confirmaCargo__return);


        }
        {
        System.out.println("Invoking tiempoEntregaAbonoRastreo...");
        java.lang.Integer _tiempoEntregaAbonoRastreo_fechaOperacion = null;
        java.lang.String _tiempoEntregaAbonoRastreo_rastreo = "";
        java.lang.Integer _tiempoEntregaAbonoRastreo_instContraparte = null;
        java.lang.Long _tiempoEntregaAbonoRastreo__return = port.tiempoEntregaAbonoRastreo(_tiempoEntregaAbonoRastreo_fechaOperacion, _tiempoEntregaAbonoRastreo_rastreo, _tiempoEntregaAbonoRastreo_instContraparte);
        System.out.println("tiempoEntregaAbonoRastreo.result=" + _tiempoEntregaAbonoRastreo__return);


        }
        {
        System.out.println("Invoking devuelveOrden...");
        java.lang.Integer _devuelveOrden_idOrden = null;
        java.lang.Integer _devuelveOrden_causaDevolucion = null;
        java.lang.String _devuelveOrden_nuevoRastreo = "";
        java.lang.Integer _devuelveOrden_medioEntrega = null;
        java.lang.String _devuelveOrden_usuario = "";
        com.lgec.enlacefi.spei.integration.h2h.SpeiServiceResponse _devuelveOrden__return = port.devuelveOrden(_devuelveOrden_idOrden, _devuelveOrden_causaDevolucion, _devuelveOrden_nuevoRastreo, _devuelveOrden_medioEntrega, _devuelveOrden_usuario);
        System.out.println("devuelveOrden.result=" + _devuelveOrden__return);


        }
        {
        System.out.println("Invoking estadoOperaciones...");
        java.lang.String _estadoOperaciones_empresa = "";
        boolean _estadoOperaciones_recorreSubempresas = false;
        java.lang.String _estadoOperaciones_estados = "";
        java.lang.String _estadoOperaciones_tipoOperacion = "";
        com.lgec.enlacefi.spei.integration.h2h.EstadoOperacionesResponseWS _estadoOperaciones__return = port.estadoOperaciones(_estadoOperaciones_empresa, _estadoOperaciones_recorreSubempresas, _estadoOperaciones_estados, _estadoOperaciones_tipoOperacion);
        System.out.println("estadoOperaciones.result=" + _estadoOperaciones__return);


        }
        {
        System.out.println("Invoking traspasoEntreCuentas...");
        java.lang.String _traspasoEntreCuentas_cuentaOrigen = "";
        java.lang.String _traspasoEntreCuentas_cuentaDestino = "";
        java.lang.String _traspasoEntreCuentas_monto = "";
        java.lang.String _traspasoEntreCuentas_usuario = "";
        com.lgec.enlacefi.spei.integration.h2h.SpeiServiceResponse _traspasoEntreCuentas__return = port.traspasoEntreCuentas(_traspasoEntreCuentas_cuentaOrigen, _traspasoEntreCuentas_cuentaDestino, _traspasoEntreCuentas_monto, _traspasoEntreCuentas_usuario);
        System.out.println("traspasoEntreCuentas.result=" + _traspasoEntreCuentas__return);


        }
        {
        System.out.println("Invoking confirmaAbono...");
        java.lang.Integer _confirmaAbono_fechaOperacion = null;
        java.lang.Integer _confirmaAbono_institucionContraparte = null;
        java.lang.String _confirmaAbono_claveRastreo = "";
        java.lang.String _confirmaAbono_rfc = "";
        com.lgec.enlacefi.spei.integration.h2h.SpeiServiceResponse _confirmaAbono__return = port.confirmaAbono(_confirmaAbono_fechaOperacion, _confirmaAbono_institucionContraparte, _confirmaAbono_claveRastreo, _confirmaAbono_rfc);
        System.out.println("confirmaAbono.result=" + _confirmaAbono__return);


        }
        {
        System.out.println("Invoking consultaNominaTesofeFechaOperacion...");
        java.lang.Integer _consultaNominaTesofeFechaOperacion_institucion = null;
        java.lang.Integer _consultaNominaTesofeFechaOperacion_fechaOperacion = null;
        com.lgec.enlacefi.spei.integration.h2h.NominaTesofeWS _consultaNominaTesofeFechaOperacion__return = port.consultaNominaTesofeFechaOperacion(_consultaNominaTesofeFechaOperacion_institucion, _consultaNominaTesofeFechaOperacion_fechaOperacion);
        System.out.println("consultaNominaTesofeFechaOperacion.result=" + _consultaNominaTesofeFechaOperacion__return);


        }
        {
        System.out.println("Invoking confirmaAbonoDelay...");
        java.lang.Integer _confirmaAbonoDelay_idEF = null;
        java.lang.String _confirmaAbonoDelay_rfc = "";
        java.lang.Long _confirmaAbonoDelay_delay = null;
        com.lgec.enlacefi.spei.integration.h2h.SpeiServiceResponse _confirmaAbonoDelay__return = port.confirmaAbonoDelay(_confirmaAbonoDelay_idEF, _confirmaAbonoDelay_rfc, _confirmaAbonoDelay_delay);
        System.out.println("confirmaAbonoDelay.result=" + _confirmaAbonoDelay__return);


        }
        {
        System.out.println("Invoking tiempoEntregaCargoRastreo...");
        java.lang.Integer _tiempoEntregaCargoRastreo_fechaOperacion = null;
        java.lang.String _tiempoEntregaCargoRastreo_rastreo = "";
        java.lang.Integer _tiempoEntregaCargoRastreo_instOperante = null;
        java.lang.Long _tiempoEntregaCargoRastreo__return = port.tiempoEntregaCargoRastreo(_tiempoEntregaCargoRastreo_fechaOperacion, _tiempoEntregaCargoRastreo_rastreo, _tiempoEntregaCargoRastreo_instOperante);
        System.out.println("tiempoEntregaCargoRastreo.result=" + _tiempoEntregaCargoRastreo__return);


        }
        {
        System.out.println("Invoking consultaOrdenes...");
        java.lang.String _consultaOrdenes_tipoOrden = "";
        java.lang.Integer _consultaOrdenes_fechaLiqInicial = null;
        java.lang.Integer _consultaOrdenes_fechaLiqFinal = null;
        java.lang.Integer _consultaOrdenes_institucionOperante = null;
        java.lang.Integer _consultaOrdenes_institucionCotraparte = null;
        java.lang.String _consultaOrdenes_nombreOrdenante = "";
        java.lang.String _consultaOrdenes_nombreBeneficiario = "";
        java.lang.String _consultaOrdenes_cveRastreo = "";
        java.lang.String _consultaOrdenes_cuentaOrdenante = "";
        java.lang.String _consultaOrdenes_cuentaBeneficiario = "";
        java.math.BigDecimal _consultaOrdenes_monto = new java.math.BigDecimal("0");
        java.util.List<com.lgec.enlacefi.spei.integration.h2h.OrdenPagoWS> _consultaOrdenes__return = port.consultaOrdenes(_consultaOrdenes_tipoOrden, _consultaOrdenes_fechaLiqInicial, _consultaOrdenes_fechaLiqFinal, _consultaOrdenes_institucionOperante, _consultaOrdenes_institucionCotraparte, _consultaOrdenes_nombreOrdenante, _consultaOrdenes_nombreBeneficiario, _consultaOrdenes_cveRastreo, _consultaOrdenes_cuentaOrdenante, _consultaOrdenes_cuentaBeneficiario, _consultaOrdenes_monto);
        System.out.println("consultaOrdenes.result=" + _consultaOrdenes__return);


        }
        {
        System.out.println("Invoking registraOrden...");
        com.lgec.enlacefi.spei.integration.h2h.OrdenPagoWS _registraOrden_ordenPago = null;
        com.lgec.enlacefi.spei.integration.h2h.SpeiServiceResponse _registraOrden__return = port.registraOrden(_registraOrden_ordenPago);
        System.out.println("registraOrden.result=" + _registraOrden__return);


        }
        {
        System.out.println("Invoking tiempoEntregaAbono...");
        java.lang.Integer _tiempoEntregaAbono_idOrden = null;
        java.lang.Long _tiempoEntregaAbono__return = port.tiempoEntregaAbono(_tiempoEntregaAbono_idOrden);
        System.out.println("tiempoEntregaAbono.result=" + _tiempoEntregaAbono__return);


        }
        {
        System.out.println("Invoking consultaOrdenEnviadaRastreo...");
        java.lang.Integer _consultaOrdenEnviadaRastreo_fechaOperacion = null;
        java.lang.Integer _consultaOrdenEnviadaRastreo_operante = null;
        java.lang.String _consultaOrdenEnviadaRastreo_rastreo = "";
        com.lgec.enlacefi.spei.integration.h2h.OrdenPagoWS _consultaOrdenEnviadaRastreo__return = port.consultaOrdenEnviadaRastreo(_consultaOrdenEnviadaRastreo_fechaOperacion, _consultaOrdenEnviadaRastreo_operante, _consultaOrdenEnviadaRastreo_rastreo);
        System.out.println("consultaOrdenEnviadaRastreo.result=" + _consultaOrdenEnviadaRastreo__return);


        }
        {
        System.out.println("Invoking consultaNominaTesofe...");
        java.lang.Integer _consultaNominaTesofe_institucion = null;
        com.lgec.enlacefi.spei.integration.h2h.NominaTesofeWS _consultaNominaTesofe__return = port.consultaNominaTesofe(_consultaNominaTesofe_institucion);
        System.out.println("consultaNominaTesofe.result=" + _consultaNominaTesofe__return);


        }
        {
        System.out.println("Invoking registraDetalleErrorEnvio...");
        java.lang.Integer _registraDetalleErrorEnvio_id = null;
        java.lang.String _registraDetalleErrorEnvio_detalleError = "";
        port.registraDetalleErrorEnvio(_registraDetalleErrorEnvio_id, _registraDetalleErrorEnvio_detalleError);


        }
        {
        System.out.println("Invoking registraOrdenes...");
        java.util.List<com.lgec.enlacefi.spei.integration.h2h.OrdenPagoWS> _registraOrdenes_ordenesPago = null;
        java.util.List<com.lgec.enlacefi.spei.integration.h2h.SpeiServiceResponse> _registraOrdenes__return = port.registraOrdenes(_registraOrdenes_ordenesPago);
        System.out.println("registraOrdenes.result=" + _registraOrdenes__return);


        }
        {
        System.out.println("Invoking confirmaAbonoId...");
        java.lang.Integer _confirmaAbonoId_idEF = null;
        java.lang.String _confirmaAbonoId_rfc = "";
        com.lgec.enlacefi.spei.integration.h2h.SpeiServiceResponse _confirmaAbonoId__return = port.confirmaAbonoId(_confirmaAbonoId_idEF, _confirmaAbonoId_rfc);
        System.out.println("confirmaAbonoId.result=" + _confirmaAbonoId__return);


        }
        {
        System.out.println("Invoking consultaOrdenRecibida...");
        java.lang.Integer _consultaOrdenRecibida_idOrden = null;
        com.lgec.enlacefi.spei.integration.h2h.OrdenPagoWS _consultaOrdenRecibida__return = port.consultaOrdenRecibida(_consultaOrdenRecibida_idOrden);
        System.out.println("consultaOrdenRecibida.result=" + _consultaOrdenRecibida__return);


        }

        System.exit(0);
    }

}
