package com.tim.one.validator

import org.springframework.beans.factory.annotation.Autowired
import org.springframework.test.context.ContextConfiguration
import org.springframework.transaction.annotation.Transactional

import spock.lang.Specification
import spock.lang.Unroll

import com.tim.one.command.CreateAccountCommand
import com.tim.one.command.PaypalPaymentCommand
import com.tim.one.command.ProjectChangeStatusCommand
import com.tim.one.command.ProjectCreateCommand
import com.tim.one.command.TransferAccountCommand

import com.tim.one.model.ProjectType

@ContextConfiguration(locations=[
	"classpath:/services-appctx.xml",
	"classpath:/persistence-appctx.xml",
	"classpath:/jms-appctx.xml",
	"classpath:/mail-context.xml",
	"classpath:/transaction-appctx.xml",
	"classpath:/formatter-appctx.xml",
	"classpath:/stp-appctx.xml",
	"classpath:/aop-appctx.xml",
	"classpath:/properties-appctx.xml"])

@Transactional
public class ProjectCreateCommandValidatorIntegrationSpec extends Specification {

	@Autowired
	CommandValidator validator

	@Unroll
	def """When we have an project with id #id, and name as #name and this parameters: #userId, #subcategory, #inclosure,
  #showground, #banner, #avatar, #videoLink1, #videoLink2, #videoLink3, #videoLink4, #videoLink5, #soundCloudLink1, 
  #soundCloudLink2, #soundCloudLink3, #soundCloudLink4, #soundCloudLink5, #description, #cast, #url, #status,
  #videoPublic, #audioPublic, #imagePublic, #infoPublic and
  when we validate we expecting that result is: #result"""() {
		given: "An change status command"
		def command = new ProjectCreateCommand()
		when: "We assing values to command"
		command.id = id
		command.userId = userId
		command.subcategory = subcategory
		command.name = name
		command.inclosure = inclosure
		command.showground = showground
		command.banner = banner
		command.avatar = avatar
		command.videoLink1 = videoLink1
		command.videoLink2 = videoLink2
		command.videoLink3 = videoLink3
		command.videoLink4 = videoLink4
		command.videoLink5 = videoLink5
		command.soundCloudLink1 = soundCloudLink1
		command.soundCloudLink2 = soundCloudLink2
		command.soundCloudLink3 = soundCloudLink3
		command.soundCloudLink4 = soundCloudLink4
		command.soundCloudLink5 = soundCloudLink5
		command.description = description
		command.cast = cast
		command.url = url
		command.status = status
		command.videoPublic = videoPublic
		command.audioPublic = audioPublic
		command.imagePublic = imagePublic
		command.infoPublic = infoPublic
		then:"We expect the following results"
		result == validator.isValid(command)
		where:"We have the next cases"
		id | userId	| subcategory |	name     | inclosure	 | showground   | banner  | avatar   | videoLink1   																 | videoLink2   																 | videoLink3   																 | videoLink4   																 | videoLink5   																 | soundCloudLink1   													 | soundCloudLink2   													 | soundCloudLink3   													 | soundCloudLink4   													 | soundCloudLink5   													 | description   | cast   | url   									  | status | videoPublic | audioPublic | imagePublic | infoPublic || result
		1	 | 2  		| 6           | "name"   | "inclosure" | "showground" | "baner" | "avatar" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "description" | "cast" | "http://www.math.uio.no/" | 0      | 0           | 0           | 0           | 0          || true
		0	 | 2  		| 6           | "name"   | "inclosure" | "showground" | "baner" | "avatar" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "description" | "cast" | "http://www.math.uio.no/" | 0      | 0           | 0           | 0           | 0          || false
		1	 | 0  		| 6           | "name"   | "inclosure" | "showground" | "baner" | "avatar" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "description" | "cast" | "http://www.math.uio.no/" | 0      | 0           | 0           | 0           | 0          || false
		1	 | 2  		| 0           | "name"   | "inclosure" | "showground" | "baner" | "avatar" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "description" | "cast" | "http://www.math.uio.no/" | 0      | 0           | 0           | 0           | 0          || false
		1	 | 2  		| 41          | "name"   | "inclosure" | "showground" | "baner" | "avatar" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "description" | "cast" | "http://www.math.uio.no/" | 0      | 0           | 0           | 0           | 0          || false
		1	 | 2  		| 6           | ""       | "inclosure" | "showground" | "baner" | "avatar" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "description" | "cast" | "http://www.math.uio.no/" | 0      | 0           | 0           | 0           | 0          || false
		1	 | 2  		| 6           | null     | "inclosure" | "showground" | "baner" | "avatar" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "description" | "cast" | "http://www.math.uio.no/" | 0      | 0           | 0           | 0           | 0          || false
		1	 | 2  		| 6           | "name"   | "inclosure" | "showground" | "baner" | "avatar" | "url" 																				 | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "description" | "cast" | "http://www.math.uio.no/" | 0      | 0           | 0           | 0           | 0          || false
		1	 | 2  		| 6           | "name"   | "inclosure" | "showground" | "baner" | "avatar" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "url" 																				 | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "description" | "cast" | "http://www.math.uio.no/" | 0      | 0           | 0           | 0           | 0          || false
		1	 | 2  		| 6           | "name"   | "inclosure" | "showground" | "baner" | "avatar" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "url" 																				 | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "description" | "cast" | "http://www.math.uio.no/" | 0      | 0           | 0           | 0           | 0          || false
		1	 | 2  		| 6           | "name"   | "inclosure" | "showground" | "baner" | "avatar" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "url" 																				 | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "description" | "cast" | "http://www.math.uio.no/" | 0      | 0           | 0           | 0           | 0          || false
		1	 | 2  		| 6           | "name"   | "inclosure" | "showground" | "baner" | "avatar" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "url" 																				 | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "description" | "cast" | "http://www.math.uio.no/" | 0      | 0           | 0           | 0           | 0          || false
		1	 | 2  		| 6           | "name"   | "inclosure" | "showground" | "baner" | "avatar" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "url" 																			 | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "description" | "cast" | "http://www.math.uio.no/" | 0      | 0           | 0           | 0           | 0          || false
		1	 | 2  		| 6           | "name"   | "inclosure" | "showground" | "baner" | "avatar" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://soundcloud.com/josdem/sweet-dunes" | "url" 																			 | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "description" | "cast" | "http://www.math.uio.no/" | 0      | 0           | 0           | 0           | 0          || false
		1	 | 2  		| 6           | "name"   | "inclosure" | "showground" | "baner" | "avatar" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "url" 																			 | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "description" | "cast" | "http://www.math.uio.no/" | 0      | 0           | 0           | 0           | 0          || false
		1	 | 2  		| 6           | "name"   | "inclosure" | "showground" | "baner" | "avatar" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "url" 																			 | "https://soundcloud.com/josdem/sweet-dunes" | "description" | "cast" | "http://www.math.uio.no/" | 0      | 0           | 0           | 0           | 0          || false
		1	 | 2  		| 6           | "name"   | "inclosure" | "showground" | "baner" | "avatar" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "url" 																			 | "description" | "cast" | "http://www.math.uio.no/" | 0      | 0           | 0           | 0           | 0          || false
		1	 | 2  		| 6           | "name"   | "inclosure" | "showground" | "baner" | "avatar" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "description" | "cast" | "url" 										| 0      | 0           | 0           | 0           | 0          || false
		1	 | 2  		| 6           | "name"   | "inclosure" | "showground" | "baner" | "avatar" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "description" | "cast" | "http://www.math.uio.no/" | 12     | 0           | 0           | 0           | 0          || false
		1	 | 2  		| 6           | "name"   | "inclosure" | "showground" | "baner" | "avatar" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "description" | "cast" | "http://www.math.uio.no/" | 0      | 2           | 0           | 0           | 0          || false
		1	 | 2  		| 6           | "name"   | "inclosure" | "showground" | "baner" | "avatar" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "description" | "cast" | "http://www.math.uio.no/" | 0      | 0           | 2           | 0           | 0          || false
		1	 | 2  		| 6           | "name"   | "inclosure" | "showground" | "baner" | "avatar" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "description" | "cast" | "http://www.math.uio.no/" | 0      | 0           | 0           | 2           | 0          || false
		1	 | 2  		| 6           | "name"   | "inclosure" | "showground" | "baner" | "avatar" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "description" | "cast" | "http://www.math.uio.no/" | 0      | 0           | 0           | 0           | 2          || false
		1	 | 2  		| 6           | "<script>alert('hello josdem')</script>"   | "inclosure" | "showground" | "baner" | "avatar" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "description" | "cast" | "http://www.math.uio.no/" | 0      | 0           | 0           | 0           | 0          || false
		1	 | 2  		| 6           | "name"   | "<script>alert('hello josdem')</script>" | "showground" | "baner" | "avatar" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "description" | "cast" | "http://www.math.uio.no/" | 0      | 0           | 0           | 0           | 0          || false
		1	 | 2  		| 6           | "name"   | "inclosure" | "<script>alert('hello josdem')</script>" | "baner" | "avatar" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "description" | "cast" | "http://www.math.uio.no/" | 0      | 0           | 0           | 0           | 0          || false
		1	 | 2  		| 6           | "name"   | "inclosure" | "showground" | "<script>alert('hello josdem')</script>" | "avatar" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "description" | "cast" | "http://www.math.uio.no/" | 0      | 0           | 0           | 0           | 0          || false
		1	 | 2  		| 6           | "name"   | "inclosure" | "showground" | "baner" | "<script>alert('hello josdem')</script>" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "description" | "cast" | "http://www.math.uio.no/" | 0      | 0           | 0           | 0           | 0          || false
		1	 | 2  		| 6           | "name"   | "inclosure" | "showground" | "baner" | "avatar" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "<script>alert('hello josdem')</script>" | "cast" | "http://www.math.uio.no/" | 0      | 0           | 0           | 0           | 0          || false
		1	 | 2  		| 6           | "name"   | "inclosure" | "showground" | "baner" | "avatar" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://www.youtube.com/watch?v=x72b5ngHJU0" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "https://soundcloud.com/josdem/sweet-dunes" | "description" | "<script>alert('hello josdem')</script>" | "http://www.math.uio.no/" | 0      | 0           | 0           | 0           | 0          || false
 	}
	
}

