package com.tim.one.bean;

public enum MessageType {
	ABONO_CUENTA, TRASPASO_CUENTA_BENEFICIARIO, FINANCIAMIENTO, INVERSION, PRODUCTOR, CIERRE_PRODUCTOR, 
	CIERRE_ADMINISTRADOR, RETORNO_FONDOS_DOCUMENTACION_INCOMPLETA, BE_ADMINISTRADOR, BE_PRODUCTOR, CIERRE_PRODUCTO, 
	CIERRE_PRODUCTO_PRODUCTOR, REDENCION, RETORNO_FONDOS_NO_ENTREGA_PRODUCTO, BAJA_DOCUMENTACION, 
	CIERRE_PUBLICACION_PRODUCTOR, CIERRE_PUBLICACION_SOCIO, BE_SOCIO, CIERRE_VENTA_PRODUCTOR, TRASPASO_CUENTA_ORDENANTE, CASHOUT,
	BRIDGE_TRAMA,CREACION_CUENTA,FORGOT_PASSWORD
}
