package com.tim.one.bean;

public enum TramaAccountType {
	PRODUCT, 
	PROJECT_REJECTED, 
	INVESTMENT, 
	TRANSFER_TO_BRIDGE, 
	TRANSFER_TO_PARTNER, 
	TRANSFER_TO_TRAMA, 
	CASH_IN_TO_TRAMA,
	CASH_OUT_TO_USER
}
