package com.tim.one.bean;

public enum ProjectTxType {
	PRODUCER_PARTNERSHIP, 
	PRODUCER_PAYMENT, 
	PRODUCER_FUNDING, 
	RETURN_FUNDS, 
	RETURN_TRAMA_FEE, 
	REDEEM_OUT, 
	REDEEM_IN, 
	FUNDING, 
	INVESTMENT, 
	TRANSFER_FROM_TRAMA, 
	PROVIDER_PAYMENT, 
	PROVIDER_PARTNERSHIP, 
	PROVIDER_RETURN_CAPITAL, 
	TRAMA_FEE, 
	BOX_OFFICE_SALES, 
	RDF,
	RDI
}
